// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class BackupRecordEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.BackupRecord",
                typeof(BackupRecord),
                baseEntityType,
                propertyCount: 13,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(BackupRecord).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var attempts = runtimeEntityType.AddProperty(
                "Attempts",
                typeof(int),
                propertyInfo: typeof(BackupRecord).GetProperty("Attempts", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<Attempts>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            attempts.AddAnnotation("Relational:ColumnName", "attempts");
            attempts.AddAnnotation("Relational:DefaultValue", 0);

            var checksum = runtimeEntityType.AddProperty(
                "Checksum",
                typeof(string),
                propertyInfo: typeof(BackupRecord).GetProperty("Checksum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<Checksum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            checksum.AddAnnotation("Relational:ColumnName", "checksum");

            var cloudKey = runtimeEntityType.AddProperty(
                "CloudKey",
                typeof(string),
                propertyInfo: typeof(BackupRecord).GetProperty("CloudKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<CloudKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            cloudKey.AddAnnotation("Relational:ColumnName", "cloud_key");

            var cloudStatus = runtimeEntityType.AddProperty(
                "CloudStatus",
                typeof(string),
                propertyInfo: typeof(BackupRecord).GetProperty("CloudStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<CloudStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            cloudStatus.AddAnnotation("Relational:ColumnName", "cloud_status");

            var filename = runtimeEntityType.AddProperty(
                "Filename",
                typeof(string),
                propertyInfo: typeof(BackupRecord).GetProperty("Filename", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<Filename>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            filename.AddAnnotation("Relational:ColumnName", "filename");

            var lastError = runtimeEntityType.AddProperty(
                "LastError",
                typeof(string),
                propertyInfo: typeof(BackupRecord).GetProperty("LastError", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<LastError>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastError.AddAnnotation("Relational:ColumnName", "last_error");

            var localPath = runtimeEntityType.AddProperty(
                "LocalPath",
                typeof(string),
                propertyInfo: typeof(BackupRecord).GetProperty("LocalPath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<LocalPath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            localPath.AddAnnotation("Relational:ColumnName", "local_path");

            var schemaVer = runtimeEntityType.AddProperty(
                "SchemaVer",
                typeof(string),
                propertyInfo: typeof(BackupRecord).GetProperty("SchemaVer", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<SchemaVer>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            schemaVer.AddAnnotation("Relational:ColumnName", "schema_ver");

            var sizeBytes = runtimeEntityType.AddProperty(
                "SizeBytes",
                typeof(long),
                propertyInfo: typeof(BackupRecord).GetProperty("SizeBytes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<SizeBytes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            sizeBytes.AddAnnotation("Relational:ColumnName", "size_bytes");

            var takenAt = runtimeEntityType.AddProperty(
                "TakenAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(BackupRecord).GetProperty("TakenAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<TakenAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            takenAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            takenAt.AddAnnotation("Relational:ColumnName", "taken_at");
            takenAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var usbStatus = runtimeEntityType.AddProperty(
                "UsbStatus",
                typeof(string),
                propertyInfo: typeof(BackupRecord).GetProperty("UsbStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<UsbStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            usbStatus.AddAnnotation("Relational:ColumnName", "usb_status");

            var verifiedAt = runtimeEntityType.AddProperty(
                "VerifiedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(BackupRecord).GetProperty("VerifiedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BackupRecord).GetField("<VerifiedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new Iso8601TimestampConverter());
            verifiedAt.AddAnnotation("Relational:ColumnName", "verified_at");
            verifiedAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_backup_record");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "backup_record");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
