// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class CreditNoteEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.CreditNote",
                typeof(CreditNote),
                baseEntityType,
                propertyCount: 9,
                foreignKeyCount: 2,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(CreditNote).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var amountIssued = runtimeEntityType.AddProperty(
                "AmountIssued",
                typeof(Money),
                propertyInfo: typeof(CreditNote).GetProperty("AmountIssued", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<AmountIssued>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            amountIssued.SetSentinelFromProviderValue(0L);
            amountIssued.AddAnnotation("Relational:ColumnName", "amount_issued");
            amountIssued.AddAnnotation("Relational:ColumnType", "INTEGER");

            var amountRemaining = runtimeEntityType.AddProperty(
                "AmountRemaining",
                typeof(Money),
                propertyInfo: typeof(CreditNote).GetProperty("AmountRemaining", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<AmountRemaining>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            amountRemaining.SetSentinelFromProviderValue(0L);
            amountRemaining.AddAnnotation("Relational:ColumnName", "amount_remaining");
            amountRemaining.AddAnnotation("Relational:ColumnType", "INTEGER");

            var customerId = runtimeEntityType.AddProperty(
                "CustomerId",
                typeof(long?),
                propertyInfo: typeof(CreditNote).GetProperty("CustomerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<CustomerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            customerId.AddAnnotation("Relational:ColumnName", "customer_id");

            var expiresOn = runtimeEntityType.AddProperty(
                "ExpiresOn",
                typeof(string),
                propertyInfo: typeof(CreditNote).GetProperty("ExpiresOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<ExpiresOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            expiresOn.AddAnnotation("Relational:ColumnName", "expires_on");
            expiresOn.AddAnnotation("Relational:ColumnType", "TEXT");

            var issuedAt = runtimeEntityType.AddProperty(
                "IssuedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(CreditNote).GetProperty("IssuedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<IssuedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            issuedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            issuedAt.AddAnnotation("Relational:ColumnName", "issued_at");
            issuedAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var number = runtimeEntityType.AddProperty(
                "Number",
                typeof(string),
                propertyInfo: typeof(CreditNote).GetProperty("Number", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<Number>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            number.AddAnnotation("Relational:ColumnName", "number");

            var saleReturnId = runtimeEntityType.AddProperty(
                "SaleReturnId",
                typeof(long),
                propertyInfo: typeof(CreditNote).GetProperty("SaleReturnId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<SaleReturnId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            saleReturnId.AddAnnotation("Relational:ColumnName", "sale_return_id");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(string),
                propertyInfo: typeof(CreditNote).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CreditNote).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            status.AddAnnotation("Relational:ColumnName", "status");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_credit_note");

            var index = runtimeEntityType.AddIndex(
                new[] { number },
                unique: true);
            index.AddAnnotation("Relational:Name", "ux_credit_note_number");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CustomerId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_credit_note_customer_customer_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SaleReturnId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_credit_note_sale_return_sale_return_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "credit_note");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
