// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class DailySalesSummaryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.DailySalesSummary",
                typeof(DailySalesSummary),
                baseEntityType,
                propertyCount: 13,
                keyCount: 1);

            var businessDate = runtimeEntityType.AddProperty(
                "BusinessDate",
                typeof(string),
                propertyInfo: typeof(DailySalesSummary).GetProperty("BusinessDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<BusinessDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            businessDate.AddAnnotation("Relational:ColumnName", "business_date");
            businessDate.AddAnnotation("Relational:ColumnType", "TEXT");

            var billCount = runtimeEntityType.AddProperty(
                "BillCount",
                typeof(long),
                propertyInfo: typeof(DailySalesSummary).GetProperty("BillCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<BillCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            billCount.AddAnnotation("Relational:ColumnName", "bill_count");

            var builtAt = runtimeEntityType.AddProperty(
                "BuiltAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(DailySalesSummary).GetProperty("BuiltAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<BuiltAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            builtAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            builtAt.AddAnnotation("Relational:ColumnName", "built_at");
            builtAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var cogs = runtimeEntityType.AddProperty(
                "Cogs",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("Cogs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<Cogs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            cogs.SetSentinelFromProviderValue(0L);
            cogs.AddAnnotation("Relational:ColumnName", "cogs");
            cogs.AddAnnotation("Relational:ColumnType", "INTEGER");

            var discount = runtimeEntityType.AddProperty(
                "Discount",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("Discount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<Discount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            discount.SetSentinelFromProviderValue(0L);
            discount.AddAnnotation("Relational:ColumnName", "discount");
            discount.AddAnnotation("Relational:ColumnType", "INTEGER");

            var gross = runtimeEntityType.AddProperty(
                "Gross",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("Gross", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<Gross>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            gross.SetSentinelFromProviderValue(0L);
            gross.AddAnnotation("Relational:ColumnName", "gross");
            gross.AddAnnotation("Relational:ColumnType", "INTEGER");

            var net = runtimeEntityType.AddProperty(
                "Net",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("Net", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<Net>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            net.SetSentinelFromProviderValue(0L);
            net.AddAnnotation("Relational:ColumnName", "net");
            net.AddAnnotation("Relational:ColumnType", "INTEGER");

            var returnCount = runtimeEntityType.AddProperty(
                "ReturnCount",
                typeof(long),
                propertyInfo: typeof(DailySalesSummary).GetProperty("ReturnCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<ReturnCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            returnCount.AddAnnotation("Relational:ColumnName", "return_count");

            var returnValue = runtimeEntityType.AddProperty(
                "ReturnValue",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("ReturnValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<ReturnValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            returnValue.SetSentinelFromProviderValue(0L);
            returnValue.AddAnnotation("Relational:ColumnName", "return_value");
            returnValue.AddAnnotation("Relational:ColumnType", "INTEGER");

            var tax = runtimeEntityType.AddProperty(
                "Tax",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("Tax", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<Tax>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tax.SetSentinelFromProviderValue(0L);
            tax.AddAnnotation("Relational:ColumnName", "tax");
            tax.AddAnnotation("Relational:ColumnType", "INTEGER");

            var tenderCard = runtimeEntityType.AddProperty(
                "TenderCard",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("TenderCard", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<TenderCard>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tenderCard.SetSentinelFromProviderValue(0L);
            tenderCard.AddAnnotation("Relational:ColumnName", "tender_card");
            tenderCard.AddAnnotation("Relational:ColumnType", "INTEGER");

            var tenderCash = runtimeEntityType.AddProperty(
                "TenderCash",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("TenderCash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<TenderCash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tenderCash.SetSentinelFromProviderValue(0L);
            tenderCash.AddAnnotation("Relational:ColumnName", "tender_cash");
            tenderCash.AddAnnotation("Relational:ColumnType", "INTEGER");

            var tenderOther = runtimeEntityType.AddProperty(
                "TenderOther",
                typeof(Money),
                propertyInfo: typeof(DailySalesSummary).GetProperty("TenderOther", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DailySalesSummary).GetField("<TenderOther>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tenderOther.SetSentinelFromProviderValue(0L);
            tenderOther.AddAnnotation("Relational:ColumnName", "tender_other");
            tenderOther.AddAnnotation("Relational:ColumnType", "INTEGER");

            var key = runtimeEntityType.AddKey(
                new[] { businessDate });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_daily_sales_summary");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "daily_sales_summary");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
