// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class GoodsReceiptLineEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.GoodsReceiptLine",
                typeof(GoodsReceiptLine),
                baseEntityType,
                propertyCount: 10,
                foreignKeyCount: 3,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var goodsReceiptId = runtimeEntityType.AddProperty(
                "GoodsReceiptId",
                typeof(long),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("GoodsReceiptId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<GoodsReceiptId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            goodsReceiptId.AddAnnotation("Relational:ColumnName", "goods_receipt_id");

            var lineTotal = runtimeEntityType.AddProperty(
                "LineTotal",
                typeof(Money),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("LineTotal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<LineTotal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            lineTotal.SetSentinelFromProviderValue(0L);
            lineTotal.AddAnnotation("Relational:ColumnName", "line_total");
            lineTotal.AddAnnotation("Relational:ColumnType", "INTEGER");

            var productVariantId = runtimeEntityType.AddProperty(
                "ProductVariantId",
                typeof(long),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("ProductVariantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<ProductVariantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            productVariantId.AddAnnotation("Relational:ColumnName", "product_variant_id");

            var qty = runtimeEntityType.AddProperty(
                "Qty",
                typeof(long),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("Qty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<Qty>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            qty.AddAnnotation("Relational:ColumnName", "qty");

            var qtyBase = runtimeEntityType.AddProperty(
                "QtyBase",
                typeof(long),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("QtyBase", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<QtyBase>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            qtyBase.AddAnnotation("Relational:ColumnName", "qty_base");

            var tax = runtimeEntityType.AddProperty(
                "Tax",
                typeof(Money),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("Tax", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<Tax>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tax.SetSentinelFromProviderValue(0L);
            tax.AddAnnotation("Relational:ColumnName", "tax");
            tax.AddAnnotation("Relational:ColumnType", "INTEGER");
            tax.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var unitCost = runtimeEntityType.AddProperty(
                "UnitCost",
                typeof(Money),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("UnitCost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<UnitCost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            unitCost.SetSentinelFromProviderValue(0L);
            unitCost.AddAnnotation("Relational:ColumnName", "unit_cost");
            unitCost.AddAnnotation("Relational:ColumnType", "INTEGER");

            var unitCostBase = runtimeEntityType.AddProperty(
                "UnitCostBase",
                typeof(Money),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("UnitCostBase", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<UnitCostBase>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            unitCostBase.SetSentinelFromProviderValue(0L);
            unitCostBase.AddAnnotation("Relational:ColumnName", "unit_cost_base");
            unitCostBase.AddAnnotation("Relational:ColumnType", "INTEGER");

            var uomId = runtimeEntityType.AddProperty(
                "UomId",
                typeof(long),
                propertyInfo: typeof(GoodsReceiptLine).GetProperty("UomId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceiptLine).GetField("<UomId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            uomId.AddAnnotation("Relational:ColumnName", "uom_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_goods_receipt_line");

            var index = runtimeEntityType.AddIndex(
                new[] { goodsReceiptId });
            index.AddAnnotation("Relational:Name", "ix_grn_line_grn");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("GoodsReceiptId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_goods_receipt_line_goods_receipt_goods_receipt_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ProductVariantId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_goods_receipt_line_product_variant_product_variant_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UomId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_goods_receipt_line_uom_uom_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "goods_receipt_line");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
