// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class GoodsReceiptEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.GoodsReceipt",
                typeof(GoodsReceipt),
                baseEntityType,
                propertyCount: 12,
                foreignKeyCount: 3,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(GoodsReceipt).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var grnNo = runtimeEntityType.AddProperty(
                "GrnNo",
                typeof(string),
                propertyInfo: typeof(GoodsReceipt).GetProperty("GrnNo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<GrnNo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            grnNo.AddAnnotation("Relational:ColumnName", "grn_no");

            var note = runtimeEntityType.AddProperty(
                "Note",
                typeof(string),
                propertyInfo: typeof(GoodsReceipt).GetProperty("Note", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<Note>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            note.AddAnnotation("Relational:ColumnName", "note");

            var otherCost = runtimeEntityType.AddProperty(
                "OtherCost",
                typeof(Money),
                propertyInfo: typeof(GoodsReceipt).GetProperty("OtherCost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<OtherCost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            otherCost.SetSentinelFromProviderValue(0L);
            otherCost.AddAnnotation("Relational:ColumnName", "other_cost");
            otherCost.AddAnnotation("Relational:ColumnType", "INTEGER");
            otherCost.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var purchaseOrderId = runtimeEntityType.AddProperty(
                "PurchaseOrderId",
                typeof(long?),
                propertyInfo: typeof(GoodsReceipt).GetProperty("PurchaseOrderId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<PurchaseOrderId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            purchaseOrderId.AddAnnotation("Relational:ColumnName", "purchase_order_id");

            var receivedAt = runtimeEntityType.AddProperty(
                "ReceivedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(GoodsReceipt).GetProperty("ReceivedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<ReceivedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            receivedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            receivedAt.AddAnnotation("Relational:ColumnName", "received_at");
            receivedAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var subtotal = runtimeEntityType.AddProperty(
                "Subtotal",
                typeof(Money),
                propertyInfo: typeof(GoodsReceipt).GetProperty("Subtotal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<Subtotal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            subtotal.SetSentinelFromProviderValue(0L);
            subtotal.AddAnnotation("Relational:ColumnName", "subtotal");
            subtotal.AddAnnotation("Relational:ColumnType", "INTEGER");

            var supplierId = runtimeEntityType.AddProperty(
                "SupplierId",
                typeof(long),
                propertyInfo: typeof(GoodsReceipt).GetProperty("SupplierId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<SupplierId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            supplierId.AddAnnotation("Relational:ColumnName", "supplier_id");

            var supplierInvNo = runtimeEntityType.AddProperty(
                "SupplierInvNo",
                typeof(string),
                propertyInfo: typeof(GoodsReceipt).GetProperty("SupplierInvNo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<SupplierInvNo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            supplierInvNo.AddAnnotation("Relational:ColumnName", "supplier_inv_no");

            var tax = runtimeEntityType.AddProperty(
                "Tax",
                typeof(Money),
                propertyInfo: typeof(GoodsReceipt).GetProperty("Tax", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<Tax>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tax.SetSentinelFromProviderValue(0L);
            tax.AddAnnotation("Relational:ColumnName", "tax");
            tax.AddAnnotation("Relational:ColumnType", "INTEGER");
            tax.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var total = runtimeEntityType.AddProperty(
                "Total",
                typeof(Money),
                propertyInfo: typeof(GoodsReceipt).GetProperty("Total", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<Total>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            total.SetSentinelFromProviderValue(0L);
            total.AddAnnotation("Relational:ColumnName", "total");
            total.AddAnnotation("Relational:ColumnType", "INTEGER");

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(long),
                propertyInfo: typeof(GoodsReceipt).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GoodsReceipt).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            userId.AddAnnotation("Relational:ColumnName", "user_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_goods_receipt");

            var index = runtimeEntityType.AddIndex(
                new[] { grnNo },
                unique: true);
            index.AddAnnotation("Relational:Name", "ux_grn_no");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("PurchaseOrderId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_goods_receipt_purchase_order_purchase_order_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SupplierId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_goods_receipt_supplier_supplier_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_goods_receipt_app_user_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "goods_receipt");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
