// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    public partial class PosDbContextModel
    {
        private PosDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("442ebf1e-493e-4c91-9c06-e451008ab644"), entityTypeCount: 40)
        {
        }

        partial void Initialize()
        {
            var appSetting = AppSettingEntityType.Create(this);
            var appUser = AppUserEntityType.Create(this);
            var auditLog = AuditLogEntityType.Create(this);
            var backupRecord = BackupRecordEntityType.Create(this);
            var barcode = BarcodeEntityType.Create(this);
            var brand = BrandEntityType.Create(this);
            var cashMovement = CashMovementEntityType.Create(this);
            var category = CategoryEntityType.Create(this);
            var creditNote = CreditNoteEntityType.Create(this);
            var creditNoteRedemption = CreditNoteRedemptionEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var dailyProductSummary = DailyProductSummaryEntityType.Create(this);
            var dailySalesSummary = DailySalesSummaryEntityType.Create(this);
            var goodsReceipt = GoodsReceiptEntityType.Create(this);
            var goodsReceiptLine = GoodsReceiptLineEntityType.Create(this);
            var heldBill = HeldBillEntityType.Create(this);
            var numberSequence = NumberSequenceEntityType.Create(this);
            var payment = PaymentEntityType.Create(this);
            var priceChangeLog = PriceChangeLogEntityType.Create(this);
            var priceTier = PriceTierEntityType.Create(this);
            var printJob = PrintJobEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var productSupplier = ProductSupplierEntityType.Create(this);
            var productUom = ProductUomEntityType.Create(this);
            var productVariant = ProductVariantEntityType.Create(this);
            var purchaseOrder = PurchaseOrderEntityType.Create(this);
            var purchaseOrderLine = PurchaseOrderLineEntityType.Create(this);
            var sale = SaleEntityType.Create(this);
            var saleLine = SaleLineEntityType.Create(this);
            var saleReturn = SaleReturnEntityType.Create(this);
            var saleReturnLine = SaleReturnLineEntityType.Create(this);
            var shift = ShiftEntityType.Create(this);
            var stockBalance = StockBalanceEntityType.Create(this);
            var stockMovement = StockMovementEntityType.Create(this);
            var stockTake = StockTakeEntityType.Create(this);
            var stockTakeLine = StockTakeLineEntityType.Create(this);
            var supplier = SupplierEntityType.Create(this);
            var taxClass = TaxClassEntityType.Create(this);
            var uom = UomEntityType.Create(this);
            var schemaVersion = SchemaVersionEntityType.Create(this);

            AppSettingEntityType.CreateForeignKey1(appSetting, appUser);
            AuditLogEntityType.CreateForeignKey1(auditLog, appUser);
            BarcodeEntityType.CreateForeignKey1(barcode, productVariant);
            CashMovementEntityType.CreateForeignKey1(cashMovement, shift);
            CashMovementEntityType.CreateForeignKey2(cashMovement, appUser);
            CategoryEntityType.CreateForeignKey1(category, category);
            CreditNoteEntityType.CreateForeignKey1(creditNote, customer);
            CreditNoteEntityType.CreateForeignKey2(creditNote, saleReturn);
            CreditNoteRedemptionEntityType.CreateForeignKey1(creditNoteRedemption, creditNote);
            CreditNoteRedemptionEntityType.CreateForeignKey2(creditNoteRedemption, sale);
            DailyProductSummaryEntityType.CreateForeignKey1(dailyProductSummary, productVariant);
            GoodsReceiptEntityType.CreateForeignKey1(goodsReceipt, purchaseOrder);
            GoodsReceiptEntityType.CreateForeignKey2(goodsReceipt, supplier);
            GoodsReceiptEntityType.CreateForeignKey3(goodsReceipt, appUser);
            GoodsReceiptLineEntityType.CreateForeignKey1(goodsReceiptLine, goodsReceipt);
            GoodsReceiptLineEntityType.CreateForeignKey2(goodsReceiptLine, productVariant);
            GoodsReceiptLineEntityType.CreateForeignKey3(goodsReceiptLine, uom);
            HeldBillEntityType.CreateForeignKey1(heldBill, appUser);
            PaymentEntityType.CreateForeignKey1(payment, sale);
            PriceChangeLogEntityType.CreateForeignKey1(priceChangeLog, productVariant);
            PriceChangeLogEntityType.CreateForeignKey2(priceChangeLog, appUser);
            PriceTierEntityType.CreateForeignKey1(priceTier, productVariant);
            ProductEntityType.CreateForeignKey1(product, uom);
            ProductEntityType.CreateForeignKey2(product, brand);
            ProductEntityType.CreateForeignKey3(product, category);
            ProductEntityType.CreateForeignKey4(product, taxClass);
            ProductSupplierEntityType.CreateForeignKey1(productSupplier, product);
            ProductSupplierEntityType.CreateForeignKey2(productSupplier, supplier);
            ProductUomEntityType.CreateForeignKey1(productUom, product);
            ProductUomEntityType.CreateForeignKey2(productUom, uom);
            ProductVariantEntityType.CreateForeignKey1(productVariant, product);
            PurchaseOrderEntityType.CreateForeignKey1(purchaseOrder, supplier);
            PurchaseOrderEntityType.CreateForeignKey2(purchaseOrder, appUser);
            PurchaseOrderLineEntityType.CreateForeignKey1(purchaseOrderLine, productVariant);
            PurchaseOrderLineEntityType.CreateForeignKey2(purchaseOrderLine, purchaseOrder);
            PurchaseOrderLineEntityType.CreateForeignKey3(purchaseOrderLine, uom);
            SaleEntityType.CreateForeignKey1(sale, appUser);
            SaleEntityType.CreateForeignKey2(sale, shift);
            SaleEntityType.CreateForeignKey3(sale, appUser);
            SaleLineEntityType.CreateForeignKey1(saleLine, productVariant);
            SaleLineEntityType.CreateForeignKey2(saleLine, sale);
            SaleLineEntityType.CreateForeignKey3(saleLine, uom);
            SaleReturnEntityType.CreateForeignKey1(saleReturn, appUser);
            SaleReturnEntityType.CreateForeignKey2(saleReturn, customer);
            SaleReturnEntityType.CreateForeignKey3(saleReturn, sale);
            SaleReturnEntityType.CreateForeignKey4(saleReturn, sale);
            SaleReturnEntityType.CreateForeignKey5(saleReturn, shift);
            SaleReturnEntityType.CreateForeignKey6(saleReturn, appUser);
            SaleReturnLineEntityType.CreateForeignKey1(saleReturnLine, productVariant);
            SaleReturnLineEntityType.CreateForeignKey2(saleReturnLine, saleLine);
            SaleReturnLineEntityType.CreateForeignKey3(saleReturnLine, saleReturn);
            ShiftEntityType.CreateForeignKey1(shift, appUser);
            ShiftEntityType.CreateForeignKey2(shift, appUser);
            StockBalanceEntityType.CreateForeignKey1(stockBalance, productVariant);
            StockMovementEntityType.CreateForeignKey1(stockMovement, productVariant);
            StockMovementEntityType.CreateForeignKey2(stockMovement, appUser);
            StockTakeEntityType.CreateForeignKey1(stockTake, appUser);
            StockTakeLineEntityType.CreateForeignKey1(stockTakeLine, productVariant);
            StockTakeLineEntityType.CreateForeignKey2(stockTakeLine, stockTake);

            AppSettingEntityType.CreateAnnotations(appSetting);
            AppUserEntityType.CreateAnnotations(appUser);
            AuditLogEntityType.CreateAnnotations(auditLog);
            BackupRecordEntityType.CreateAnnotations(backupRecord);
            BarcodeEntityType.CreateAnnotations(barcode);
            BrandEntityType.CreateAnnotations(brand);
            CashMovementEntityType.CreateAnnotations(cashMovement);
            CategoryEntityType.CreateAnnotations(category);
            CreditNoteEntityType.CreateAnnotations(creditNote);
            CreditNoteRedemptionEntityType.CreateAnnotations(creditNoteRedemption);
            CustomerEntityType.CreateAnnotations(customer);
            DailyProductSummaryEntityType.CreateAnnotations(dailyProductSummary);
            DailySalesSummaryEntityType.CreateAnnotations(dailySalesSummary);
            GoodsReceiptEntityType.CreateAnnotations(goodsReceipt);
            GoodsReceiptLineEntityType.CreateAnnotations(goodsReceiptLine);
            HeldBillEntityType.CreateAnnotations(heldBill);
            NumberSequenceEntityType.CreateAnnotations(numberSequence);
            PaymentEntityType.CreateAnnotations(payment);
            PriceChangeLogEntityType.CreateAnnotations(priceChangeLog);
            PriceTierEntityType.CreateAnnotations(priceTier);
            PrintJobEntityType.CreateAnnotations(printJob);
            ProductEntityType.CreateAnnotations(product);
            ProductSupplierEntityType.CreateAnnotations(productSupplier);
            ProductUomEntityType.CreateAnnotations(productUom);
            ProductVariantEntityType.CreateAnnotations(productVariant);
            PurchaseOrderEntityType.CreateAnnotations(purchaseOrder);
            PurchaseOrderLineEntityType.CreateAnnotations(purchaseOrderLine);
            SaleEntityType.CreateAnnotations(sale);
            SaleLineEntityType.CreateAnnotations(saleLine);
            SaleReturnEntityType.CreateAnnotations(saleReturn);
            SaleReturnLineEntityType.CreateAnnotations(saleReturnLine);
            ShiftEntityType.CreateAnnotations(shift);
            StockBalanceEntityType.CreateAnnotations(stockBalance);
            StockMovementEntityType.CreateAnnotations(stockMovement);
            StockTakeEntityType.CreateAnnotations(stockTake);
            StockTakeLineEntityType.CreateAnnotations(stockTakeLine);
            SupplierEntityType.CreateAnnotations(supplier);
            TaxClassEntityType.CreateAnnotations(taxClass);
            UomEntityType.CreateAnnotations(uom);
            SchemaVersionEntityType.CreateAnnotations(schemaVersion);

            AddAnnotation("ProductVersion", "10.0.0");
        }
    }
}
