// <auto-generated />
using Counterpoint.Infrastructure.Data;
using Counterpoint.Infrastructure.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(PosDbContext), typeof(PosDbContextModel))]
