// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class PrintJobEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.PrintJob",
                typeof(PrintJob),
                baseEntityType,
                propertyCount: 12,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(PrintJob).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var attempts = runtimeEntityType.AddProperty(
                "Attempts",
                typeof(int),
                propertyInfo: typeof(PrintJob).GetProperty("Attempts", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<Attempts>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            attempts.AddAnnotation("Relational:ColumnName", "attempts");
            attempts.AddAnnotation("Relational:DefaultValue", 0);

            var copies = runtimeEntityType.AddProperty(
                "Copies",
                typeof(int),
                propertyInfo: typeof(PrintJob).GetProperty("Copies", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<Copies>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            copies.AddAnnotation("Relational:ColumnName", "copies");
            copies.AddAnnotation("Relational:DefaultValue", 1);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(PrintJob).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            createdAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");
            createdAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var docId = runtimeEntityType.AddProperty(
                "DocId",
                typeof(long?),
                propertyInfo: typeof(PrintJob).GetProperty("DocId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<DocId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            docId.AddAnnotation("Relational:ColumnName", "doc_id");

            var docType = runtimeEntityType.AddProperty(
                "DocType",
                typeof(string),
                propertyInfo: typeof(PrintJob).GetProperty("DocType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<DocType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            docType.AddAnnotation("Relational:ColumnName", "doc_type");

            var isDuplicate = runtimeEntityType.AddProperty(
                "IsDuplicate",
                typeof(bool),
                propertyInfo: typeof(PrintJob).GetProperty("IsDuplicate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<IsDuplicate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isDuplicate.AddAnnotation("Relational:ColumnName", "is_duplicate");
            isDuplicate.AddAnnotation("Relational:DefaultValue", false);

            var lastError = runtimeEntityType.AddProperty(
                "LastError",
                typeof(string),
                propertyInfo: typeof(PrintJob).GetProperty("LastError", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<LastError>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastError.AddAnnotation("Relational:ColumnName", "last_error");

            var payload = runtimeEntityType.AddProperty(
                "Payload",
                typeof(byte[]),
                propertyInfo: typeof(PrintJob).GetProperty("Payload", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<Payload>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            payload.AddAnnotation("Relational:ColumnName", "payload");
            payload.AddAnnotation("Relational:ColumnType", "BLOB");

            var printedAt = runtimeEntityType.AddProperty(
                "PrintedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(PrintJob).GetProperty("PrintedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<PrintedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new Iso8601TimestampConverter());
            printedAt.AddAnnotation("Relational:ColumnName", "printed_at");
            printedAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(string),
                propertyInfo: typeof(PrintJob).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            status.AddAnnotation("Relational:ColumnName", "status");

            var target = runtimeEntityType.AddProperty(
                "Target",
                typeof(string),
                propertyInfo: typeof(PrintJob).GetProperty("Target", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrintJob).GetField("<Target>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            target.AddAnnotation("Relational:ColumnName", "target");
            target.AddAnnotation("Relational:DefaultValue", "RECEIPT");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_print_job");

            var index = runtimeEntityType.AddIndex(
                new[] { status });
            index.AddAnnotation("Relational:Filter", "status = 'PENDING'");
            index.AddAnnotation("Relational:Name", "ix_print_pending");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "print_job");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
