// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class PurchaseOrderLineEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.PurchaseOrderLine",
                typeof(PurchaseOrderLine),
                baseEntityType,
                propertyCount: 7,
                foreignKeyCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(PurchaseOrderLine).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PurchaseOrderLine).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var productVariantId = runtimeEntityType.AddProperty(
                "ProductVariantId",
                typeof(long),
                propertyInfo: typeof(PurchaseOrderLine).GetProperty("ProductVariantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PurchaseOrderLine).GetField("<ProductVariantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            productVariantId.AddAnnotation("Relational:ColumnName", "product_variant_id");

            var purchaseOrderId = runtimeEntityType.AddProperty(
                "PurchaseOrderId",
                typeof(long),
                propertyInfo: typeof(PurchaseOrderLine).GetProperty("PurchaseOrderId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PurchaseOrderLine).GetField("<PurchaseOrderId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            purchaseOrderId.AddAnnotation("Relational:ColumnName", "purchase_order_id");

            var qty = runtimeEntityType.AddProperty(
                "Qty",
                typeof(long),
                propertyInfo: typeof(PurchaseOrderLine).GetProperty("Qty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PurchaseOrderLine).GetField("<Qty>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            qty.AddAnnotation("Relational:ColumnName", "qty");

            var qtyReceivedBase = runtimeEntityType.AddProperty(
                "QtyReceivedBase",
                typeof(long),
                propertyInfo: typeof(PurchaseOrderLine).GetProperty("QtyReceivedBase", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PurchaseOrderLine).GetField("<QtyReceivedBase>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            qtyReceivedBase.AddAnnotation("Relational:ColumnName", "qty_received_base");
            qtyReceivedBase.AddAnnotation("Relational:DefaultValue", 0L);

            var unitCost = runtimeEntityType.AddProperty(
                "UnitCost",
                typeof(Money),
                propertyInfo: typeof(PurchaseOrderLine).GetProperty("UnitCost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PurchaseOrderLine).GetField("<UnitCost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            unitCost.SetSentinelFromProviderValue(0L);
            unitCost.AddAnnotation("Relational:ColumnName", "unit_cost");
            unitCost.AddAnnotation("Relational:ColumnType", "INTEGER");

            var uomId = runtimeEntityType.AddProperty(
                "UomId",
                typeof(long),
                propertyInfo: typeof(PurchaseOrderLine).GetProperty("UomId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PurchaseOrderLine).GetField("<UomId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            uomId.AddAnnotation("Relational:ColumnName", "uom_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_purchase_order_line");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ProductVariantId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_purchase_order_line_product_variant_product_variant_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("PurchaseOrderId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_purchase_order_line_purchase_order_purchase_order_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UomId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_purchase_order_line_uom_uom_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "purchase_order_line");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
