// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SaleReturnEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.SaleReturn",
                typeof(SaleReturn),
                baseEntityType,
                propertyCount: 18,
                foreignKeyCount: 6,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(SaleReturn).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var authorisedBy = runtimeEntityType.AddProperty(
                "AuthorisedBy",
                typeof(long?),
                propertyInfo: typeof(SaleReturn).GetProperty("AuthorisedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<AuthorisedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            authorisedBy.AddAnnotation("Relational:ColumnName", "authorised_by");

            var businessDate = runtimeEntityType.AddProperty(
                "BusinessDate",
                typeof(string),
                propertyInfo: typeof(SaleReturn).GetProperty("BusinessDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<BusinessDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            businessDate.AddAnnotation("Relational:ColumnName", "business_date");
            businessDate.AddAnnotation("Relational:ColumnType", "TEXT");

            var customerId = runtimeEntityType.AddProperty(
                "CustomerId",
                typeof(long?),
                propertyInfo: typeof(SaleReturn).GetProperty("CustomerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<CustomerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            customerId.AddAnnotation("Relational:ColumnName", "customer_id");

            var exchangeSaleId = runtimeEntityType.AddProperty(
                "ExchangeSaleId",
                typeof(long?),
                propertyInfo: typeof(SaleReturn).GetProperty("ExchangeSaleId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<ExchangeSaleId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            exchangeSaleId.AddAnnotation("Relational:ColumnName", "exchange_sale_id");

            var originalSaleId = runtimeEntityType.AddProperty(
                "OriginalSaleId",
                typeof(long?),
                propertyInfo: typeof(SaleReturn).GetProperty("OriginalSaleId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<OriginalSaleId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            originalSaleId.AddAnnotation("Relational:ColumnName", "original_sale_id");

            var prevHash = runtimeEntityType.AddProperty(
                "PrevHash",
                typeof(string),
                propertyInfo: typeof(SaleReturn).GetProperty("PrevHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<PrevHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            prevHash.AddAnnotation("Relational:ColumnName", "prev_hash");

            var reason = runtimeEntityType.AddProperty(
                "Reason",
                typeof(string),
                propertyInfo: typeof(SaleReturn).GetProperty("Reason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<Reason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            reason.AddAnnotation("Relational:ColumnName", "reason");

            var refundMethod = runtimeEntityType.AddProperty(
                "RefundMethod",
                typeof(string),
                propertyInfo: typeof(SaleReturn).GetProperty("RefundMethod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<RefundMethod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            refundMethod.AddAnnotation("Relational:ColumnName", "refund_method");

            var restockingFee = runtimeEntityType.AddProperty(
                "RestockingFee",
                typeof(Money),
                propertyInfo: typeof(SaleReturn).GetProperty("RestockingFee", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<RestockingFee>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            restockingFee.SetSentinelFromProviderValue(0L);
            restockingFee.AddAnnotation("Relational:ColumnName", "restocking_fee");
            restockingFee.AddAnnotation("Relational:ColumnType", "INTEGER");
            restockingFee.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var returnNo = runtimeEntityType.AddProperty(
                "ReturnNo",
                typeof(string),
                propertyInfo: typeof(SaleReturn).GetProperty("ReturnNo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<ReturnNo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            returnNo.AddAnnotation("Relational:ColumnName", "return_no");

            var returnedAt = runtimeEntityType.AddProperty(
                "ReturnedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SaleReturn).GetProperty("ReturnedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<ReturnedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            returnedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            returnedAt.AddAnnotation("Relational:ColumnName", "returned_at");
            returnedAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var rowHash = runtimeEntityType.AddProperty(
                "RowHash",
                typeof(string),
                propertyInfo: typeof(SaleReturn).GetProperty("RowHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<RowHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            rowHash.AddAnnotation("Relational:ColumnName", "row_hash");

            var shiftId = runtimeEntityType.AddProperty(
                "ShiftId",
                typeof(long),
                propertyInfo: typeof(SaleReturn).GetProperty("ShiftId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<ShiftId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            shiftId.AddAnnotation("Relational:ColumnName", "shift_id");

            var subtotal = runtimeEntityType.AddProperty(
                "Subtotal",
                typeof(Money),
                propertyInfo: typeof(SaleReturn).GetProperty("Subtotal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<Subtotal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            subtotal.SetSentinelFromProviderValue(0L);
            subtotal.AddAnnotation("Relational:ColumnName", "subtotal");
            subtotal.AddAnnotation("Relational:ColumnType", "INTEGER");

            var tax = runtimeEntityType.AddProperty(
                "Tax",
                typeof(Money),
                propertyInfo: typeof(SaleReturn).GetProperty("Tax", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<Tax>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tax.SetSentinelFromProviderValue(0L);
            tax.AddAnnotation("Relational:ColumnName", "tax");
            tax.AddAnnotation("Relational:ColumnType", "INTEGER");
            tax.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var totalRefund = runtimeEntityType.AddProperty(
                "TotalRefund",
                typeof(Money),
                propertyInfo: typeof(SaleReturn).GetProperty("TotalRefund", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<TotalRefund>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            totalRefund.SetSentinelFromProviderValue(0L);
            totalRefund.AddAnnotation("Relational:ColumnName", "total_refund");
            totalRefund.AddAnnotation("Relational:ColumnType", "INTEGER");

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(long),
                propertyInfo: typeof(SaleReturn).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturn).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            userId.AddAnnotation("Relational:ColumnName", "user_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_sale_return");

            var index = runtimeEntityType.AddIndex(
                new[] { businessDate });
            index.AddAnnotation("Relational:Name", "ix_return_date");

            var index0 = runtimeEntityType.AddIndex(
                new[] { originalSaleId });
            index0.AddAnnotation("Relational:Name", "ix_return_sale");

            var index1 = runtimeEntityType.AddIndex(
                new[] { returnNo },
                unique: true);
            index1.AddAnnotation("Relational:Name", "ux_return_no");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("AuthorisedBy") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_app_user_authorised_by");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CustomerId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_customer_customer_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ExchangeSaleId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_sale_exchange_sale_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("OriginalSaleId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_sale_original_sale_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey5(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ShiftId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_shift_shift_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey6(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_app_user_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "sale_return");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
