// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SaleLineEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.SaleLine",
                typeof(SaleLine),
                baseEntityType,
                propertyCount: 16,
                foreignKeyCount: 3,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(SaleLine).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(SaleLine).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            description.AddAnnotation("Relational:ColumnName", "description");

            var discount = runtimeEntityType.AddProperty(
                "Discount",
                typeof(Money),
                propertyInfo: typeof(SaleLine).GetProperty("Discount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<Discount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            discount.SetSentinelFromProviderValue(0L);
            discount.AddAnnotation("Relational:ColumnName", "discount");
            discount.AddAnnotation("Relational:ColumnType", "INTEGER");
            discount.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var lineNo = runtimeEntityType.AddProperty(
                "LineNo",
                typeof(int),
                propertyInfo: typeof(SaleLine).GetProperty("LineNo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<LineNo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            lineNo.AddAnnotation("Relational:ColumnName", "line_no");

            var lineTotal = runtimeEntityType.AddProperty(
                "LineTotal",
                typeof(Money),
                propertyInfo: typeof(SaleLine).GetProperty("LineTotal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<LineTotal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            lineTotal.SetSentinelFromProviderValue(0L);
            lineTotal.AddAnnotation("Relational:ColumnName", "line_total");
            lineTotal.AddAnnotation("Relational:ColumnType", "INTEGER");

            var note = runtimeEntityType.AddProperty(
                "Note",
                typeof(string),
                propertyInfo: typeof(SaleLine).GetProperty("Note", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<Note>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            note.AddAnnotation("Relational:ColumnName", "note");

            var productVariantId = runtimeEntityType.AddProperty(
                "ProductVariantId",
                typeof(long?),
                propertyInfo: typeof(SaleLine).GetProperty("ProductVariantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<ProductVariantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            productVariantId.AddAnnotation("Relational:ColumnName", "product_variant_id");

            var qty = runtimeEntityType.AddProperty(
                "Qty",
                typeof(long),
                propertyInfo: typeof(SaleLine).GetProperty("Qty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<Qty>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            qty.AddAnnotation("Relational:ColumnName", "qty");

            var qtyBase = runtimeEntityType.AddProperty(
                "QtyBase",
                typeof(long),
                propertyInfo: typeof(SaleLine).GetProperty("QtyBase", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<QtyBase>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            qtyBase.AddAnnotation("Relational:ColumnName", "qty_base");

            var qtyReturned = runtimeEntityType.AddProperty(
                "QtyReturned",
                typeof(long),
                propertyInfo: typeof(SaleLine).GetProperty("QtyReturned", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<QtyReturned>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            qtyReturned.AddAnnotation("Relational:ColumnName", "qty_returned");
            qtyReturned.AddAnnotation("Relational:DefaultValue", 0L);

            var saleId = runtimeEntityType.AddProperty(
                "SaleId",
                typeof(long),
                propertyInfo: typeof(SaleLine).GetProperty("SaleId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<SaleId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            saleId.AddAnnotation("Relational:ColumnName", "sale_id");

            var tax = runtimeEntityType.AddProperty(
                "Tax",
                typeof(Money),
                propertyInfo: typeof(SaleLine).GetProperty("Tax", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<Tax>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tax.SetSentinelFromProviderValue(0L);
            tax.AddAnnotation("Relational:ColumnName", "tax");
            tax.AddAnnotation("Relational:ColumnType", "INTEGER");
            tax.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var taxRate = runtimeEntityType.AddProperty(
                "TaxRate",
                typeof(TaxRate),
                propertyInfo: typeof(SaleLine).GetProperty("TaxRate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<TaxRate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledTaxRateConverter());
            taxRate.SetSentinelFromProviderValue(0L);
            taxRate.AddAnnotation("Relational:ColumnName", "tax_rate");
            taxRate.AddAnnotation("Relational:ColumnType", "INTEGER");
            taxRate.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.TaxRate.FromScaled(0L));

            var unitCost = runtimeEntityType.AddProperty(
                "UnitCost",
                typeof(Money),
                propertyInfo: typeof(SaleLine).GetProperty("UnitCost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<UnitCost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            unitCost.SetSentinelFromProviderValue(0L);
            unitCost.AddAnnotation("Relational:ColumnName", "unit_cost");
            unitCost.AddAnnotation("Relational:ColumnType", "INTEGER");
            unitCost.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var unitPrice = runtimeEntityType.AddProperty(
                "UnitPrice",
                typeof(Money),
                propertyInfo: typeof(SaleLine).GetProperty("UnitPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<UnitPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            unitPrice.SetSentinelFromProviderValue(0L);
            unitPrice.AddAnnotation("Relational:ColumnName", "unit_price");
            unitPrice.AddAnnotation("Relational:ColumnType", "INTEGER");

            var uomId = runtimeEntityType.AddProperty(
                "UomId",
                typeof(long),
                propertyInfo: typeof(SaleLine).GetProperty("UomId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleLine).GetField("<UomId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            uomId.AddAnnotation("Relational:ColumnName", "uom_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_sale_line");

            var index = runtimeEntityType.AddIndex(
                new[] { saleId });
            index.AddAnnotation("Relational:Name", "ix_sale_line_sale");

            var index0 = runtimeEntityType.AddIndex(
                new[] { productVariantId, saleId });
            index0.AddAnnotation("Relational:Name", "ix_sale_line_variant");

            var index1 = runtimeEntityType.AddIndex(
                new[] { saleId, lineNo },
                unique: true);
            index1.AddAnnotation("Relational:Name", "ux_sale_line_no");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ProductVariantId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_line_product_variant_product_variant_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SaleId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_line_sale_sale_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UomId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_line_uom_uom_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "sale_line");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
