// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SaleEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.Sale",
                typeof(Sale),
                baseEntityType,
                propertyCount: 20,
                foreignKeyCount: 3,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(Sale).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var billDiscount = runtimeEntityType.AddProperty(
                "BillDiscount",
                typeof(Money),
                propertyInfo: typeof(Sale).GetProperty("BillDiscount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<BillDiscount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            billDiscount.SetSentinelFromProviderValue(0L);
            billDiscount.AddAnnotation("Relational:ColumnName", "bill_discount");
            billDiscount.AddAnnotation("Relational:ColumnType", "INTEGER");
            billDiscount.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var billNo = runtimeEntityType.AddProperty(
                "BillNo",
                typeof(string),
                propertyInfo: typeof(Sale).GetProperty("BillNo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<BillNo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            billNo.AddAnnotation("Relational:ColumnName", "bill_no");

            var businessDate = runtimeEntityType.AddProperty(
                "BusinessDate",
                typeof(string),
                propertyInfo: typeof(Sale).GetProperty("BusinessDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<BusinessDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            businessDate.AddAnnotation("Relational:ColumnName", "business_date");
            businessDate.AddAnnotation("Relational:ColumnType", "TEXT");

            var cancelledAt = runtimeEntityType.AddProperty(
                "CancelledAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(Sale).GetProperty("CancelledAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<CancelledAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new Iso8601TimestampConverter());
            cancelledAt.AddAnnotation("Relational:ColumnName", "cancelled_at");
            cancelledAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var cancelledBy = runtimeEntityType.AddProperty(
                "CancelledBy",
                typeof(long?),
                propertyInfo: typeof(Sale).GetProperty("CancelledBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<CancelledBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            cancelledBy.AddAnnotation("Relational:ColumnName", "cancelled_by");

            var cogs = runtimeEntityType.AddProperty(
                "Cogs",
                typeof(Money),
                propertyInfo: typeof(Sale).GetProperty("Cogs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<Cogs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            cogs.SetSentinelFromProviderValue(0L);
            cogs.AddAnnotation("Relational:ColumnName", "cogs");
            cogs.AddAnnotation("Relational:ColumnType", "INTEGER");
            cogs.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var customerId = runtimeEntityType.AddProperty(
                "CustomerId",
                typeof(long?),
                propertyInfo: typeof(Sale).GetProperty("CustomerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<CustomerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            customerId.AddAnnotation("Relational:ColumnName", "customer_id");

            var lineDiscount = runtimeEntityType.AddProperty(
                "LineDiscount",
                typeof(Money),
                propertyInfo: typeof(Sale).GetProperty("LineDiscount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<LineDiscount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            lineDiscount.SetSentinelFromProviderValue(0L);
            lineDiscount.AddAnnotation("Relational:ColumnName", "line_discount");
            lineDiscount.AddAnnotation("Relational:ColumnType", "INTEGER");
            lineDiscount.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var note = runtimeEntityType.AddProperty(
                "Note",
                typeof(string),
                propertyInfo: typeof(Sale).GetProperty("Note", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<Note>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            note.AddAnnotation("Relational:ColumnName", "note");

            var prevHash = runtimeEntityType.AddProperty(
                "PrevHash",
                typeof(string),
                propertyInfo: typeof(Sale).GetProperty("PrevHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<PrevHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            prevHash.AddAnnotation("Relational:ColumnName", "prev_hash");

            var rounding = runtimeEntityType.AddProperty(
                "Rounding",
                typeof(Money),
                propertyInfo: typeof(Sale).GetProperty("Rounding", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<Rounding>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            rounding.SetSentinelFromProviderValue(0L);
            rounding.AddAnnotation("Relational:ColumnName", "rounding");
            rounding.AddAnnotation("Relational:ColumnType", "INTEGER");
            rounding.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var rowHash = runtimeEntityType.AddProperty(
                "RowHash",
                typeof(string),
                propertyInfo: typeof(Sale).GetProperty("RowHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<RowHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            rowHash.AddAnnotation("Relational:ColumnName", "row_hash");

            var shiftId = runtimeEntityType.AddProperty(
                "ShiftId",
                typeof(long),
                propertyInfo: typeof(Sale).GetProperty("ShiftId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<ShiftId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            shiftId.AddAnnotation("Relational:ColumnName", "shift_id");

            var soldAt = runtimeEntityType.AddProperty(
                "SoldAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Sale).GetProperty("SoldAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<SoldAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            soldAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            soldAt.AddAnnotation("Relational:ColumnName", "sold_at");
            soldAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(string),
                propertyInfo: typeof(Sale).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            status.AddAnnotation("Relational:ColumnName", "status");

            var subtotal = runtimeEntityType.AddProperty(
                "Subtotal",
                typeof(Money),
                propertyInfo: typeof(Sale).GetProperty("Subtotal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<Subtotal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            subtotal.SetSentinelFromProviderValue(0L);
            subtotal.AddAnnotation("Relational:ColumnName", "subtotal");
            subtotal.AddAnnotation("Relational:ColumnType", "INTEGER");

            var tax = runtimeEntityType.AddProperty(
                "Tax",
                typeof(Money),
                propertyInfo: typeof(Sale).GetProperty("Tax", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<Tax>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tax.SetSentinelFromProviderValue(0L);
            tax.AddAnnotation("Relational:ColumnName", "tax");
            tax.AddAnnotation("Relational:ColumnType", "INTEGER");
            tax.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var total = runtimeEntityType.AddProperty(
                "Total",
                typeof(Money),
                propertyInfo: typeof(Sale).GetProperty("Total", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<Total>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            total.SetSentinelFromProviderValue(0L);
            total.AddAnnotation("Relational:ColumnName", "total");
            total.AddAnnotation("Relational:ColumnType", "INTEGER");

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(long),
                propertyInfo: typeof(Sale).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Sale).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            userId.AddAnnotation("Relational:ColumnName", "user_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_sale");

            var index = runtimeEntityType.AddIndex(
                new[] { billNo },
                unique: true);
            index.AddAnnotation("Relational:Name", "ux_sale_bill_no");

            var index0 = runtimeEntityType.AddIndex(
                new[] { businessDate });
            index0.AddAnnotation("Relational:Name", "ix_sale_date");

            var index1 = runtimeEntityType.AddIndex(
                new[] { customerId });
            index1.AddAnnotation("Relational:Name", "ix_sale_cust");

            var index2 = runtimeEntityType.AddIndex(
                new[] { shiftId });
            index2.AddAnnotation("Relational:Name", "ix_sale_shift");

            var index3 = runtimeEntityType.AddIndex(
                new[] { soldAt });
            index3.AddAnnotation("Relational:Name", "ix_sale_soldat");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CancelledBy") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_app_user_cancelled_by");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ShiftId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_shift_shift_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_app_user_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "sale");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
