// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SaleReturnLineEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.SaleReturnLine",
                typeof(SaleReturnLine),
                baseEntityType,
                propertyCount: 11,
                foreignKeyCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(SaleReturnLine).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var disposition = runtimeEntityType.AddProperty(
                "Disposition",
                typeof(string),
                propertyInfo: typeof(SaleReturnLine).GetProperty("Disposition", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<Disposition>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            disposition.AddAnnotation("Relational:ColumnName", "disposition");

            var lineRefund = runtimeEntityType.AddProperty(
                "LineRefund",
                typeof(Money),
                propertyInfo: typeof(SaleReturnLine).GetProperty("LineRefund", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<LineRefund>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            lineRefund.SetSentinelFromProviderValue(0L);
            lineRefund.AddAnnotation("Relational:ColumnName", "line_refund");
            lineRefund.AddAnnotation("Relational:ColumnType", "INTEGER");

            var productVariantId = runtimeEntityType.AddProperty(
                "ProductVariantId",
                typeof(long),
                propertyInfo: typeof(SaleReturnLine).GetProperty("ProductVariantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<ProductVariantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            productVariantId.AddAnnotation("Relational:ColumnName", "product_variant_id");

            var qtyBase = runtimeEntityType.AddProperty(
                "QtyBase",
                typeof(long),
                propertyInfo: typeof(SaleReturnLine).GetProperty("QtyBase", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<QtyBase>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            qtyBase.AddAnnotation("Relational:ColumnName", "qty_base");

            var reason = runtimeEntityType.AddProperty(
                "Reason",
                typeof(string),
                propertyInfo: typeof(SaleReturnLine).GetProperty("Reason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<Reason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            reason.AddAnnotation("Relational:ColumnName", "reason");

            var saleLineId = runtimeEntityType.AddProperty(
                "SaleLineId",
                typeof(long?),
                propertyInfo: typeof(SaleReturnLine).GetProperty("SaleLineId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<SaleLineId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            saleLineId.AddAnnotation("Relational:ColumnName", "sale_line_id");

            var saleReturnId = runtimeEntityType.AddProperty(
                "SaleReturnId",
                typeof(long),
                propertyInfo: typeof(SaleReturnLine).GetProperty("SaleReturnId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<SaleReturnId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            saleReturnId.AddAnnotation("Relational:ColumnName", "sale_return_id");

            var tax = runtimeEntityType.AddProperty(
                "Tax",
                typeof(Money),
                propertyInfo: typeof(SaleReturnLine).GetProperty("Tax", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<Tax>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            tax.SetSentinelFromProviderValue(0L);
            tax.AddAnnotation("Relational:ColumnName", "tax");
            tax.AddAnnotation("Relational:ColumnType", "INTEGER");
            tax.AddAnnotation("Relational:DefaultValue", global::Counterpoint.Domain.ValueObjects.Money.FromScaled(0L));

            var unitCost = runtimeEntityType.AddProperty(
                "UnitCost",
                typeof(Money),
                propertyInfo: typeof(SaleReturnLine).GetProperty("UnitCost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<UnitCost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            unitCost.SetSentinelFromProviderValue(0L);
            unitCost.AddAnnotation("Relational:ColumnName", "unit_cost");
            unitCost.AddAnnotation("Relational:ColumnType", "INTEGER");

            var unitPrice = runtimeEntityType.AddProperty(
                "UnitPrice",
                typeof(Money),
                propertyInfo: typeof(SaleReturnLine).GetProperty("UnitPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SaleReturnLine).GetField("<UnitPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            unitPrice.SetSentinelFromProviderValue(0L);
            unitPrice.AddAnnotation("Relational:ColumnName", "unit_price");
            unitPrice.AddAnnotation("Relational:ColumnType", "INTEGER");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_sale_return_line");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ProductVariantId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_line_product_variant_product_variant_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SaleLineId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_line_sale_line_sale_line_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SaleReturnId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_sale_return_line_sale_return_sale_return_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "sale_return_line");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
