// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SchemaVersionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.SchemaVersion",
                typeof(SchemaVersion),
                baseEntityType,
                propertyCount: 2,
                keyCount: 1);

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(string),
                propertyInfo: typeof(SchemaVersion).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SchemaVersion).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            version.AddAnnotation("Relational:ColumnName", "version");
            version.AddAnnotation("Relational:ColumnType", "TEXT");

            var appliedAt = runtimeEntityType.AddProperty(
                "AppliedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SchemaVersion).GetProperty("AppliedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SchemaVersion).GetField("<AppliedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            appliedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            appliedAt.AddAnnotation("Relational:ColumnName", "applied_at");
            appliedAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var key = runtimeEntityType.AddKey(
                new[] { version });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_schema_version");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "schema_version");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
