// <auto-generated />
using System;
using System.Reflection;
using Counterpoint.Domain.ValueObjects;
using Counterpoint.Infrastructure.Data.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Counterpoint.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ShiftEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Counterpoint.Infrastructure.Data.Schema.Shift",
                typeof(Shift),
                baseEntityType,
                propertyCount: 13,
                foreignKeyCount: 2,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(Shift).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "id");

            var businessDate = runtimeEntityType.AddProperty(
                "BusinessDate",
                typeof(string),
                propertyInfo: typeof(Shift).GetProperty("BusinessDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<BusinessDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            businessDate.AddAnnotation("Relational:ColumnName", "business_date");
            businessDate.AddAnnotation("Relational:ColumnType", "TEXT");

            var closedAt = runtimeEntityType.AddProperty(
                "ClosedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(Shift).GetProperty("ClosedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<ClosedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new Iso8601TimestampConverter());
            closedAt.AddAnnotation("Relational:ColumnName", "closed_at");
            closedAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var closedBy = runtimeEntityType.AddProperty(
                "ClosedBy",
                typeof(long?),
                propertyInfo: typeof(Shift).GetProperty("ClosedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<ClosedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            closedBy.AddAnnotation("Relational:ColumnName", "closed_by");

            var countedCash = runtimeEntityType.AddProperty(
                "CountedCash",
                typeof(Money?),
                propertyInfo: typeof(Shift).GetProperty("CountedCash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<CountedCash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new ScaledMoneyConverter());
            countedCash.AddAnnotation("Relational:ColumnName", "counted_cash");
            countedCash.AddAnnotation("Relational:ColumnType", "INTEGER");

            var expectedCash = runtimeEntityType.AddProperty(
                "ExpectedCash",
                typeof(Money?),
                propertyInfo: typeof(Shift).GetProperty("ExpectedCash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<ExpectedCash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new ScaledMoneyConverter());
            expectedCash.AddAnnotation("Relational:ColumnName", "expected_cash");
            expectedCash.AddAnnotation("Relational:ColumnType", "INTEGER");

            var note = runtimeEntityType.AddProperty(
                "Note",
                typeof(string),
                propertyInfo: typeof(Shift).GetProperty("Note", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<Note>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            note.AddAnnotation("Relational:ColumnName", "note");

            var openedAt = runtimeEntityType.AddProperty(
                "OpenedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Shift).GetProperty("OpenedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<OpenedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new Iso8601TimestampConverter());
            openedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000+00:00");
            openedAt.AddAnnotation("Relational:ColumnName", "opened_at");
            openedAt.AddAnnotation("Relational:ColumnType", "TEXT");

            var openingFloat = runtimeEntityType.AddProperty(
                "OpeningFloat",
                typeof(Money),
                propertyInfo: typeof(Shift).GetProperty("OpeningFloat", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<OpeningFloat>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new ScaledMoneyConverter());
            openingFloat.SetSentinelFromProviderValue(0L);
            openingFloat.AddAnnotation("Relational:ColumnName", "opening_float");
            openingFloat.AddAnnotation("Relational:ColumnType", "INTEGER");

            var shiftNo = runtimeEntityType.AddProperty(
                "ShiftNo",
                typeof(string),
                propertyInfo: typeof(Shift).GetProperty("ShiftNo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<ShiftNo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            shiftNo.AddAnnotation("Relational:ColumnName", "shift_no");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(string),
                propertyInfo: typeof(Shift).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            status.AddAnnotation("Relational:ColumnName", "status");

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(long),
                propertyInfo: typeof(Shift).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            userId.AddAnnotation("Relational:ColumnName", "user_id");

            var variance = runtimeEntityType.AddProperty(
                "Variance",
                typeof(Money?),
                propertyInfo: typeof(Shift).GetProperty("Variance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Shift).GetField("<Variance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new ScaledMoneyConverter());
            variance.AddAnnotation("Relational:ColumnName", "variance");
            variance.AddAnnotation("Relational:ColumnType", "INTEGER");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_shift");

            var index = runtimeEntityType.AddIndex(
                new[] { shiftNo },
                unique: true);
            index.AddAnnotation("Relational:Name", "ux_shift_no");

            var index0 = runtimeEntityType.AddIndex(
                new[] { status },
                unique: true);
            index0.AddAnnotation("Relational:Filter", "status = 'OPEN'");
            index0.AddAnnotation("Relational:Name", "ux_one_open_shift");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClosedBy") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_shift_app_user_closed_by");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_shift_app_user_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "shift");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
