// Conventional Commits, with the scope repurposed to carry the task id
// (e.g. "P1-T07") instead of a module name, per CLAUDE.md's commit convention.
module.exports = {
    extends: ["@commitlint/config-conventional"],
    // semantic-release's own "chore(release): x.y.z" commit carries the full
    // generated release notes as its body (see .releaserc.json), whose bullet
    // lines routinely exceed body-max-line-length. It's machine-generated by
    // a trusted plugin, not a human commit, so exempt it from linting rather
    // than relax the rule for everyone.
    ignores: [(message) => /^chore\(release\):/.test(message)],
    rules: {
        "header-max-length": [2, "always", 120],
        "scope-case": [0],
        "subject-case": [0]
    }
};
