// <auto-generated />
using Counterpoint.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Counterpoint.Infrastructure.Migrations
{
    [DbContext(typeof(PosDbContext))]
    partial class PosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<string>("LastLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login");

                    b.Property<string>("LockedUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_username");

                    b.ToTable("app_user", t =>
                        {
                            t.HasCheckConstraint("ck_app_user_role", "role IN ('CASHIER','OWNER')");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("before_json");

                    b.Property<long?>("EntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prev_hash");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("row_hash");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_time");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entity");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.NumberSequence", b =>
                {
                    b.Property<string>("DocType")
                        .HasColumnType("TEXT")
                        .HasColumnName("doc_type");

                    b.Property<long>("NextVal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_val");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prefix");

                    b.HasKey("DocType")
                        .HasName("pk_number_sequence");

                    b.ToTable("number_sequence", t =>
                        {
                            t.HasCheckConstraint("ck_number_sequence_doc_type", "doc_type IN ('SALE','RETURN','CREDIT_NOTE','GRN','PO','SHIFT','STOCK_TAKE','QUOTE')");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.Property<string>("PaidAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("paid_at");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.Property<long?>("SaleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_id");

                    b.Property<long?>("SaleReturnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_return_id");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tender_type");

                    b.HasKey("Id")
                        .HasName("pk_payment");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_payment_sale");

                    b.HasIndex("SaleReturnId")
                        .HasDatabaseName("ix_payment_return");

                    b.ToTable("payment", t =>
                        {
                            t.HasCheckConstraint("ck_payment_one_document", "(sale_id IS NOT NULL) <> (sale_return_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_payment_tender_type", "tender_type IN ('CASH','CARD','BANK_TRANSFER','CREDIT_NOTE','ON_ACCOUNT','CHEQUE')");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.PrintJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("copies");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long?>("DocId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("doc_id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("doc_type");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_duplicate");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("payload");

                    b.Property<string>("PrintedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("printed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("RECEIPT")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_print_job");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_print_pending")
                        .HasFilter("status = 'PENDING'");

                    b.ToTable("print_job", t =>
                        {
                            t.HasCheckConstraint("ck_print_job_doc_type", "doc_type IN ('SALE','RETURN','CREDIT_NOTE','X_REPORT','Z_REPORT','GRN','PO','STOCK_TAKE','LABEL','CASH_SLIP')");

                            t.HasCheckConstraint("ck_print_job_status", "status IN ('PENDING','PRINTED','FAILED')");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<long>("BaseUomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_uom_id");

                    b.Property<long?>("BrandId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brand_id");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<long>("CostAvg")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("cost_avg");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_path");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<long?>("MaxDiscountRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_discount_rate");

                    b.Property<long>("MinSellQty")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("min_sell_qty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameAlt")
                        .HasColumnType("TEXT")
                        .HasColumnName("name_alt");

                    b.Property<bool>("NonReturnable")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("non_returnable");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long>("ReorderLevel")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("reorder_level");

                    b.Property<long>("ReorderQty")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("reorder_qty");

                    b.Property<long>("TaxClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tax_class_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WarrantyDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("warranty_days");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_product_active");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_product_brand");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_product_code");

                    b.ToTable("product", t =>
                        {
                            t.HasCheckConstraint("ck_product_type", "type IN ('STANDARD','DECIMAL','SERVICE','NON_INVENTORY')");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.ProductVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("attributes");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_product_variant");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_variant_product");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_variant_sku");

                    b.ToTable("product_variant");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("BillDiscount")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("bill_discount");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bill_no");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("business_date");

                    b.Property<string>("CancelledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancelled_at");

                    b.Property<long?>("CancelledBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancelled_by");

                    b.Property<long>("Cogs")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("cogs");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_id");

                    b.Property<long>("LineDiscount")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("line_discount");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prev_hash");

                    b.Property<long>("Rounding")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("rounding");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("row_hash");

                    b.Property<long>("ShiftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shift_id");

                    b.Property<string>("SoldAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sold_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("Subtotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subtotal");

                    b.Property<long>("Tax")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("tax");

                    b.Property<long>("Total")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sale");

                    b.HasIndex("BillNo")
                        .IsUnique()
                        .HasDatabaseName("ux_sale_bill_no");

                    b.HasIndex("BusinessDate")
                        .HasDatabaseName("ix_sale_date");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sale_cust");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_sale_shift");

                    b.HasIndex("SoldAt")
                        .HasDatabaseName("ix_sale_soldat");

                    b.ToTable("sale", t =>
                        {
                            t.HasCheckConstraint("ck_sale_status", "status IN ('COMPLETED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.SaleLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("Discount")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("discount");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_no");

                    b.Property<long>("LineTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_total");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<long?>("ProductVariantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_variant_id");

                    b.Property<long>("Qty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty");

                    b.Property<long>("QtyBase")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty_base");

                    b.Property<long>("QtyReturned")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("qty_returned");

                    b.Property<long>("SaleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_id");

                    b.Property<long>("Tax")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("tax");

                    b.Property<long>("TaxRate")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("tax_rate");

                    b.Property<long>("UnitCost")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("unit_cost");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price");

                    b.Property<long>("UomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uom_id");

                    b.HasKey("Id")
                        .HasName("pk_sale_line");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_line_sale");

                    b.HasIndex("ProductVariantId", "SaleId")
                        .HasDatabaseName("ix_sale_line_variant");

                    b.HasIndex("SaleId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ux_sale_line_no");

                    b.ToTable("sale_line");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("business_date");

                    b.Property<string>("ClosedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at");

                    b.Property<long?>("ClosedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("closed_by");

                    b.Property<long?>("CountedCash")
                        .HasColumnType("INTEGER")
                        .HasColumnName("counted_cash");

                    b.Property<long?>("ExpectedCash")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expected_cash");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("OpenedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at");

                    b.Property<long>("OpeningFloat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opening_float");

                    b.Property<string>("ShiftNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<long?>("Variance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("variance");

                    b.HasKey("Id")
                        .HasName("pk_shift");

                    b.HasIndex("ShiftNo")
                        .IsUnique()
                        .HasDatabaseName("ux_shift_no");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ux_one_open_shift")
                        .HasFilter("status = 'OPEN'");

                    b.ToTable("shift", t =>
                        {
                            t.HasCheckConstraint("ck_shift_status", "status IN ('OPEN','CLOSED')");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.StockBalance", b =>
                {
                    b.Property<long>("ProductVariantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_variant_id");

                    b.Property<long>("CostAvg")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("cost_avg");

                    b.Property<long>("QtyBase")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("qty_base");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ProductVariantId")
                        .HasName("pk_stock_balance");

                    b.HasIndex("QtyBase")
                        .HasDatabaseName("ix_stock_balance_low");

                    b.ToTable("stock_balance");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balance_after");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("movement_type");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<long>("ProductVariantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_variant_id");

                    b.Property<long>("QtyBase")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty_base");

                    b.Property<long?>("RefDocId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ref_doc_id");

                    b.Property<string>("RefDocType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ref_doc_type");

                    b.Property<long>("UnitCost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_cost");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movement");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_movement_time");

                    b.HasIndex("ProductVariantId", "OccurredAt")
                        .HasDatabaseName("ix_movement_variant_time");

                    b.HasIndex("RefDocType", "RefDocId")
                        .HasDatabaseName("ix_movement_ref");

                    b.ToTable("stock_movement", t =>
                        {
                            t.HasCheckConstraint("ck_stock_movement_movement_type", "movement_type IN ('GRN','SALE','RETURN_IN','ADJUSTMENT','DAMAGE','STOCK_TAKE','BULK_BREAK_OUT','BULK_BREAK_IN','OPENING','TRANSFER_OUT','TRANSFER_IN')");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.TaxClass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Rate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rate");

                    b.HasKey("Id")
                        .HasName("pk_tax_class");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_class_name");

                    b.ToTable("tax_class");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Uom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("decimal_places");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_uom");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_uom_name");

                    b.ToTable("uom", t =>
                        {
                            t.HasCheckConstraint("ck_uom_decimal_places", "decimal_places BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.SchemaVersion", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.Property<string>("AppliedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_at");

                    b.HasKey("Version")
                        .HasName("pk_schema_version");

                    b.ToTable("schema_version", (string)null);
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.AuditLog", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_audit_log_app_user_user_id");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Payment", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_payment_sale_sale_id");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Product", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.Uom", null)
                        .WithMany()
                        .HasForeignKey("BaseUomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_product_uom_base_uom_id");

                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.TaxClass", null)
                        .WithMany()
                        .HasForeignKey("TaxClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_product_tax_class_tax_class_id");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.ProductVariant", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_product_product_id");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Sale", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_sale_app_user_cancelled_by");

                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sale_shift_shift_id");

                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sale_app_user_user_id");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.SaleLine", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_sale_line_product_variant_product_variant_id");

                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sale_line_sale_sale_id");

                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.Uom", null)
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sale_line_uom_uom_id");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.Shift", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_shift_app_user_closed_by");

                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_shift_app_user_user_id");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.StockBalance", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_stock_balance_product_variant_product_variant_id");
                });

            modelBuilder.Entity("Counterpoint.Infrastructure.Data.Schema.StockMovement", b =>
                {
                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movement_product_variant_product_variant_id");

                    b.HasOne("Counterpoint.Infrastructure.Data.Schema.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movement_app_user_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
